dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=cargo-cmd
    - RUST_BACKTRACE=1

matrix:
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: stable
    - env: TARGET=x86_64-unknown-linux-musl
      rust: stable
    - env: TARGET=x86_64-apple-darwin
      rust: stable
      os: osx
    - env: TARGET=stable-x86_64-unknown-linux-gnu
      rust: stable
    - os: windows
      env: TARGET=x86_64-pc-windows-gnu
      rust: stable

before_install:
  - set -e

install:
  - sh scripts/install.sh
  - source ~/.cargo/env || true

script:
  - bash scripts/script.sh

after_script: set +e

before_deploy:
  - sh scripts/before_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  api_key:
    secure: "pyYxlPySMgYlKxwWWyFWLalICnQlXyM3bGV/1FOoSFU8XZtg12L0pYQsi9EgI4E4E8Nro5OEyAoc/Ben6L0TKJ0MpQq98Vphb3wxGW4ob3xK2Dtwkj8SoJEfaZvQsXtsx6oFSUlkUwfFNQn03zxECPr7hOl1SRgxaUBCmB49tsF9qDaMb5DU9ewqgnm3ySyTYfp0ulq8e5ykaK5Ez42xvNQIn6Z9M1hK18yvVJH0eAi1gIMtz+JMkfsFgMZq6SglU3Waufmf6H3C5Gd42Ffl44yQrQA4l49m6m2Sne34/PXDRj2/A9YXgMLi+wMtsHCbob3m4iQQCzFp7iVABjBfYAtEE8Un6724gWUimmGeP/9AESBnSup1Ac4C1/bd8qrGQtzKUIOizIoi5E16yHhtdnQhVAdoVz8jwj/63Xt4B6PBzroR02hxMygjlmCZOeT9e+3R2UwXyp95tO/246Yn/F7UjrlGFMqPo9hGmWUEY4JnXjCjmK07W+mHlKoMVSXhsL0KqwFYF26QOl4DFvl0FTK1LshIOI0vxPkmeF7ptRKJioWVG2wErWyouMisBPqziHLcxVjEwIBTuuhRr3fQAbhPxKmA7lgHNFRXwn6FKCOEpDlwMR72uFX4pVJhb8xaGmYsd5h/7an62oauMT+gznnoCWhQTn8HUuFf1B/CVhs="
  on:
    tags: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
    on_failure: never
